

# Cloudinary - Clef Martin:
CLOUDINARY_URL: "cloudinary://741775634893866:tlaSurgsbdqLUS9VP-y3rQpR-nI@tinmartin"

# Cl√© de Nico
development:
  FB_ID: "151863338748492"
  FB_SECRET: "2cccf35844efff0067f202649fb6ec78"
production:
  FB_ID: "151863338748492"
  FB_SECRET: "2cccf35844efff0067f202649fb6ec78"

# Algolia - Clefs de Martin :
development:
  ALGOLIA_SECRET_KEY: '6fef301f8999e01837857ec583f640fd'
production:
  ALGOLIA_SECRET_KEY: '6fef301f8999e01837857ec583f640fd'

development:
  SEARCH_ONLY_API_KEY: "990f99b5fd9adb8ef29762c2504b48c3"
production:
  SEARCH_ONLY_API_KEY: "990f99b5fd9adb8ef29762c2504b48c3"

# Devise - Nico ? :
development:
  DEVISE_SECRET_KEY: "b16a0252f405ff87113be06b794fd64449337928c30fdbd05724ca1f223255137fe48085e1190aa7255f43d5f7adab5679df4dd95885addd7319b6d926b7ed03"
production:
  DEVISE_SECRET_KEY: "b16a0252f405ff87113be06b794fd64449337928c30fdbd05724ca1f223255137fe48085e1190aa7255f43d5f7adab5679df4dd95885addd7319b6d926b7ed03"

